server:
  port: 8443

spring:
  profiles:
    active: @build.profile.id@
  security:
    oauth2:
      client:
        registration:
          discord:
            client-id: ${DISCORD_CLIENT_ID}
            client-secret: ${DISCORD_CLIENT_SECRET}
            client-name: EG Pilots Discord Server
            client-authentication-method: query
            authorizationGrantType: authorization_code
            scope:
            - identify
            - email
            redirect-uri-template: '{baseUrl}/login/oauth2/code/discord'
        provider:
          discord:
            authorization-uri: https://discordapp.com/api/oauth2/authorize
            token-uri: https://discordapp.com/api/oauth2/token
            user-info-uri: https://discordapp.com/api/users/@me
            username-attribute: username
discord:
  bot:
    token: ${DISCORD_BOT_TOKEN}
---

spring:
  profiles: dev
  data:
    mongodb:
      uri: mongodb://localhost/egpilots
server:
  ssl:
    key-store: cert/keystore.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: tomcat
---
      
spring:
  profiles: test
  data:
    mongodb:
      uri: mongodb://mongo/egpilots
server:
  ssl:
    key-store: ${KEY_STORE}
    key-store-password: ${KEY_STORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: tomcat
